micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    port: 8080


---
application:
  name: tpaFinal
  port: 9000
  api:
    swagger:
      path: /swagger
      version: 3.19.4
      layout: StandaloneLayout
      urls:
        - name: api-persona
          url: /swagger/api-persona-tpa-2020-0.0.yml
  #end::application[]
  #tag::datasource[]
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db_micronaut?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC``}
    #url: jdbc:h2:file:/tmp/tpa-presentacion
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    #driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
#end::datasource[]
#tag::jpa[]
---
jpa:
  default:
    packages-to-scan:
      - 'tpaPrueba.ent'
      - 'tpaPrueba.repos'

    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]